name: comics
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_widget_from_html: ^0.14.11
  intl: ^0.17.0


flutter:
  uses-material-design: true
  assets:
    - assets/SVG/astronaut.png
    - assets/SVG/ic_books_bicolor.png
    - assets/SVG/ic_calendar_bicolor.png
    - assets/SVG/ic_movie_bicolor.png
    - assets/SVG/ic_publisher_bicolor.png
    - assets/SVG/ic_tv_bicolor.png
    - assets/SVG/astronaut.png
    - assets/SVG/navbar_comics.png
    - assets/SVG/navbar_movies.png
    - assets/SVG/navbar_search.png
    - assets/SVG/navbar_series.png
    - assets/SVG/navbar_home.png